// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZyLJe31McIW95xRiwzU3a1coio5C0pg',
    appId: '1:299401561487:web:1b12aad27e75057171f7fa',
    messagingSenderId: '299401561487',
    projectId: 'iot-home-ea3ce',
    authDomain: 'iot-home-ea3ce.firebaseapp.com',
    databaseURL: 'https://iot-home-ea3ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-home-ea3ce.firebasestorage.app',
    measurementId: 'G-4MTRQC7JSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVmmxrLa16lKbn4fRu06nffCv6O6N7hk',
    appId: '1:299401561487:android:618708baf2057cc171f7fa',
    messagingSenderId: '299401561487',
    projectId: 'iot-home-ea3ce',
    databaseURL: 'https://iot-home-ea3ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-home-ea3ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPf_O4oxI_17LWpyiE3nWsZD9qBpvcAK0',
    appId: '1:299401561487:ios:dcc701e7a4d6737571f7fa',
    messagingSenderId: '299401561487',
    projectId: 'iot-home-ea3ce',
    databaseURL: 'https://iot-home-ea3ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-home-ea3ce.firebasestorage.app',
    iosClientId: '299401561487-vckvq731ai22a98cg5gs4g638jjbdmjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.version3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPf_O4oxI_17LWpyiE3nWsZD9qBpvcAK0',
    appId: '1:299401561487:ios:dcc701e7a4d6737571f7fa',
    messagingSenderId: '299401561487',
    projectId: 'iot-home-ea3ce',
    databaseURL: 'https://iot-home-ea3ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-home-ea3ce.firebasestorage.app',
    iosClientId: '299401561487-vckvq731ai22a98cg5gs4g638jjbdmjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.version3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCZyLJe31McIW95xRiwzU3a1coio5C0pg',
    appId: '1:299401561487:web:73e05a6914c3cee671f7fa',
    messagingSenderId: '299401561487',
    projectId: 'iot-home-ea3ce',
    authDomain: 'iot-home-ea3ce.firebaseapp.com',
    databaseURL: 'https://iot-home-ea3ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-home-ea3ce.firebasestorage.app',
    measurementId: 'G-C7YT18RE01',
  );
}
